name: graphql_query_compress
description: A package that eliminates unnecessary characters from a GraphQL query, saving several bytes on requests.
repository: https://github.com/talesbarreto/dart_graphql_query_compress
version: 1.0.0

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  gql_exec: ^1.0.0
  gql_link: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
